### ISSUE TITLE
ImportError: No module named fits

### ISSUE THREAD

**Issue by prugit1** [brentjens/rm-synthesis#5]
I tried running the code in Python latest version (3.9.6), but got the following error. Kindly help me with the issue.

_**Traceback (most recent call last):
  File "C:\Users\Prudhvi\Documents\rm-synthesis-master\rmsynthesis\main.py", line 21, in <module>
    import rmsynthesis.fits as fits
ImportError: No module named fits**_

**Comment by brentjens** [comment]
Hi,

Could you please provide the exact steps you took to obtain this error?
Do you have the most recent version of astropy istalled as well?

Best wishes,
Michiel

prugit1 writes:

> I tried running the code in Python latest version (3.9.6), but got the following error. Kindly help me with the issue.
>
> _**Traceback (most recent call last):
>   File "C:\Users\Prudhvi\Documents\rm-synthesis-master\rmsynthesis\main.py", line 21, in <module>
>     import rmsynthesis.fits as fits
> ImportError: No module named fits**_


-- 
Dr. Michiel A. Brentjens
Senior Observatory Astronomer
Astron Netherlands Institute for Radio Astronomy
Oude Hoogeveensedijk 4
7991 PD Dwingeloo
The Netherlands
Office:    (+31) (0)521 - 595 781
Reception: (+31) (0)521 - 595 100
Mobile:    (+31) (0)6 - 4167 8250
***@***.***
http://www.astron.nl/~brentjens/
